apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- k8s/etcd-development.Namespace.yaml
- k8s/etcd-ca.ConfigMap.yaml
- k8s/etcd-client-tls.Secret.yaml
- k8s/etcd-client.Service.yaml
- k8s/etcd-defrag-controller.Role.yaml
- k8s/etcd-defrag-controller.RoleBinding.yaml
- k8s/etcd-defrag-controller.ServiceAccount.yaml
- k8s/etcd-discovery.Service.yaml
- k8s/etcd-metrics-ca.ConfigMap.yaml
- k8s/etcd-peer-tls.Secret.yaml
- k8s/etcd-server-tls.Secret.yaml
- k8s/etcd.PodDisruptionBudget.yaml
- k8s/etcd-development.StatefulSet.yaml